service: api-notes

# Use the serverless-webpack plugin to transpile ES6
plugins:
  # - serverless-webpack

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  layerStack: my-common-libs
  layerLibs: Libs
  layerNodejs: Nodejs

  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules:
  #     forceExclude:
  #       - ''
  #   packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

  # If you want to access to a RMDB you will need a static IP address to give a permission for that connection on the RMDB
  # therefore you need to first add a vpc with a EC2 instance which has a static IP
  # vpc:
  #   securityGroupIds:
  #     - <security group id>
  #   subnetIds:
  #     - <subnet id>

  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    userTable: ${file(../resource/dynamodb/serverless.yml):custom.tableName.userTable}
    noteTable: ${file(../resource/dynamodb/serverless.yml):custom.tableName.noteTable}

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'Fn::ImportValue': ${self:custom.stage}-UserTableArn
        - 'Fn::ImportValue': ${self:custom.stage}-NoteTableArn
    - Effect: Allow
      Action:
        - cognito-sync:*
        - cognito-identity:*
      Resource: arn:aws:cognito-identity:*:*:*
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: arn:aws:cognito-idp:*:*:*

package:
  exclude:
    - ./node_modules/**
    - addLayer.sh
    - LICENSE
    - README.md
    - setUp.sh

functions:
  - ${file(./functions.yml)}
