service: cognito

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2
package:
  exclude:
    - ./node_modules/**
    - LICENSE
    - README.md

resources:
  - ${file(./cognito-user-pool.yml)}
  - ${file(./cognito-identity-pool.yml)}